auto nextToken() { } 

Map<String, Operation> operation_from_string {
  { "lui"       , Operation::LUI       },
  { "auipc"     , Operation::AUIPC     },
  { "jal"       , Operation::JAL       },
  { "jalr"      , Operation::JALR      },
  { "beq"   	  , Operation::BEQ       },
  { "bne"   	  , Operation::BNE       },
  { "blt"   	  , Operation::BLT       },
  { "bge"   	  , Operation::BGE       },
  { "bltu"      , Operation::BLTU      },
  { "bgeu"      , Operation::BGEU      },
  { "lb"	      , Operation::LB        },
  { "lh"	      , Operation::LH        },
  { "lw"	      , Operation::LW        },
  { "lbu"	      , Operation::LBU       },
  { "lhu"	      , Operation::LHU       },
  { "sb"	      , Operation::SB        },
  { "sh"	      , Operation::SH        },
  { "sw"	      , Operation::SW        },
  { "addi"	    , Operation::ADDI      },
  { "slti"	    , Operation::SLTI      },
  { "sltiu"	    , Operation::SLTIU     },
  { "xori"	    , Operation::XORI      },
  { "ori"	      , Operation::ORI       },
  { "andi"	    , Operation::ANDI      },
  { "slli"	    , Operation::SLLI      },
  { "srli"	    , Operation::SRLI      },
  { "srai"	    , Operation::SRAI      },
  { "add"	      , Operation::ADD       },
  { "sub"	      , Operation::SUB       },
  { "sll"	      , Operation::SLL       },
  { "slt"	      , Operation::SLT       },
  { "sltu"      , Operation::SLTU      },
  { "xor"       , Operation::XOR       },
  { "srl"	      , Operation::SRL       },
  { "sra"	      , Operation::SRA       },
  { "or"	      , Operation::OR        },
  { "and"	      , Operation::AND       },
  { "fence"     , Operation::FENCE     },
  { "fence_tso" , Operation::FENCE_TSO },
  { "pause"     , Operation::PAUSE     },
  { "ecall"     , Operation::ECALL     },
  { "ebreak"    , Operation::EBREAK    },
};

auto assemble_line(String line) { }

auto assemble_program(Vector<String> lines) { for (auto line : lines) break; }
